apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    service: website
spec:
  ports:
  containers:
  - name: website
    image: yageldhn/website:latest
    ports:
    - containerPort: 5000
    - containerPort: 80
