apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    service: logstash
spec:
  ports:
  - port: 9500
    name: serving
    protocol: TCP
  - port: 5044
    name: node2node
    protocol: TCP
  selector:
    service: logstash
