apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    service: website
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: serving
  - port: 80
    protocol: TCP
    name: readfromelasticsearch
  selector:
    service: website
