#FROM openjdk:8-jdk as jdk

FROM elasticsearch:6.6.1
#COPY --from=jdk /docker-java-home /docker-java-home

#FROM elasticsearch:6.6.1
#RUN yum install -y  java-1.8.0-openjdk-devel
#RUN export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64
#RUN export PATH=$PATH:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/bin/
